[MeasureFanCPU]
Measure=Plugin
Plugin=HWiNFO
HWiNFOSensorId=0xf0008628
HWiNFOSensorInstance=0x0
HWiNFOEntryId=0x3000000
HWiNFOType=CurrentValue

[MeasureFanSystem1]
Measure=Plugin
Plugin=HWiNFO
HWiNFOSensorId=0xf0008628
HWiNFOSensorInstance=0x0
HWiNFOEntryId=0x3000004
HWiNFOType=CurrentValue

[MeasureFanSystem2]
Measure=Plugin
Plugin=HWiNFO
HWiNFOSensorId=0xf0008628
HWiNFOSensorInstance=0x0
HWiNFOEntryId=0x3000002
HWiNFOType=CurrentValue

[MeasureFanSystem3]
Measure=Plugin
Plugin=HWiNFO
HWiNFOSensorId=0xf0008628
HWiNFOSensorInstance=0x0
HWiNFOEntryId=0x3000003
HWiNFOType=CurrentValue

[MeasureFanGPU]
Measure=Plugin
Plugin=HWiNFO
HWiNFOSensorId=0xe0002000
HWiNFOSensorInstance=0x0
HWiNFOEntryId=0x3000000
HWiNFOType=CurrentValue
